### ISSUE TITLE
NPM hosting

### ISSUE THREAD

**Issue by CluEleSsUK** [elix/elix-react#1]
It'd be great if you guys could host this on npm!

**Comment by JanMiksovsky** [comment]
As you may have seen on Twitter, the Elix project is trying to gauge interest in supporting React versions of the Elix components. Because that would entail ongoing, non-trivial work, we want to get a better sense of who would use these components and why.

Can you please elaborate (here, or in email to jan@component.kitchen) on anything you think might help us understand your interest: what project do you have where you are interested in using Elix React components, how many people work on the project, etc.

Styling is also a particular question for us. Given the wide range of solutions for styling React components, we'd also like to understand how potentially-interested projects currently handle component styling.

**Comment by JanMiksovsky** [comment]
@CluEleSsUK followed up in email with great feedback. Until we're ready to commit to supporting these React components as official project artifacts, they'll have to stay experimental. Closing this issue for now.
